development:
  adapter: postgresql
  database: pcmrating_development
  host: localhost
  encoding: unicode
  port: 5432

test:
  adapter: postgresql
  database: pcmrating_test
  host: localhost
  encoding: unicode
  port: 5432

production:
  adapter: postgresql
  database: pcmrating_production
  pool: 25
  timeout: 5000
  encoding: unicode
